# Site settings

# NB! Set your site's url, otherwise nothing will work
url: "https://vincelander.github.io/"

# Google tracking id
google-tracking-id: "UA-XXXXXXXX-X"

#############
# HTML Head #
#############
lang: "en"
author: "Vince Lander Gamboa"
title: "{ Career Portfolio }"
description: "Career portfolio website of Vince Lander Gamboa."
keywords: "Data Scientist, Data Science, Analytics, Machine Learning, AI Technologies, , AI, Artificial Inteligence, Python, Data-Driven Solutions, Finance, Insurance, Retail, BPO (Business Process Outsourcing), Contact Center, Project Management, Collaboration, Certified, Generative AI, Prompt Engineering, Cloud Computing, ETL (Extract, Transform, Load), Big Data, Strategic Decision-Making, Continuous Learning, Google Cloud Platform, GCP, Vince Lander Gamboa"
favicon: "/img/favicon.png"
################
# Header layout #
################
# black-favicon: "/img/black-lab-glass.ico"
black-favicon: "/img/favicon.png"
background-img: "../img/intro-bg.jpg"
##############################
# Dynamic Text on the Header #
##############################
dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 15
start-delay: 150
delete-delay: 2750
lines: # You can add HTML Tags in the Text
  - text: "Hi, There. Thanks for paying a visit!"
  - text: "I'm Vince Lander Gamboa."
  - text: "I'm a Data Scientist."
  - text: "Data is the language of the powerholders."
  - text: "The lower you fall, the higher you'll fly."
  - text: "Whereâ€™s your will to be weird?"
me-img: "/img/author.jpg"
# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"
################
# Web app mode #
################
web-app-mode: True
# Icons for Web App mode
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"
########
# Blog #
########
post-preview-words: 96
paginate: 8
email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True
# disqus-shortname: "personal-jekyll-theme"
syntax-highlight: True
############
# Timeline #
############
events:
  - image: "/img/labtocat.png"
    date: "March 2024"
    description: "Promoted and worked as a Data & AI Consultant."
  - image: "/img/jetpacktocat.png"
    date: "December 2022"
    description: "Promoted and worked as a Data & AI Senior Analyst."
  - image: "/img/timeline/spidertocat.png"
    date: "September 2020"
    description: "Hired as a Data & AI Analyst at Accenture."
  - image: "/img/timeline/baracktocat.jpg"
    date: "November 2020"
    description: "Hired as a Data Science Research Associate at Gfk."
  - image: "/img/timeline/baracktocat.jpg"
    date: "April 2020"
    description: "Graduated with a degree, BS Information Technology at Jose Rizal University."
  - image: "/img/timeline/graduation.png"
    date: "November 2019"
    description: "Started to work as an intern."
# First image of the Timeline
timeline-img: "/img/timeline/default.png"
###########
# Contact #
###########
email: "vincelander27@gmail.com"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False
################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb:
  "Vince Lander Gamboa is a passionate Data Scientist residing in the Philippines, specializing in innovative data science projects. 
  Outside of his professional pursuits, Vince enjoys watching movies, traveling, playing guitar, and engaging in continuous learning."
author_blurb_image: "/img/author.jpg"
##################
# Social Buttons #
##################
social:
  - icon: "github"
    url: "https://github.com/vincelander"
  - icon: "linkedin-in"
    url: "https://linkedin.com/in/vince-lander-gamboa"
  # - icon: "x-twitter"
  #   url: "https://twitter.com/"
  # - icon: "rss"
  #   url: "https://le4ker.github.io/personal-jekyll-theme/feed.xml"
############
# 404 page #
############
err-404-img: "/img/labtocat.png"
################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Project: "latest-post"
  Milestone: "timeline"
  Certification: "certification"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
